name: Run Rest Assured test cases

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest  # ← switch from windows-latest to ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Print Java version
        run: java -version

      - name: Print Maven version
        run: mvn -version

      - name: Run Maven Tests
        run: mvn clean test --batch-mode --no-transfer-progress

